# Generated by Django 6.0.2 on 2026-02-14 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='retinal_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('prediction', models.IntegerField(choices=[(0, 'No Diabetic Retinopathy'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Proliferative DR')], help_text='Diabetic Retinopathy Stage')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score (0-100)')),
                ('heatmap', models.ImageField(blank=True, help_text='Grad-CAM heatmap visualization', null=True, upload_to='heatmaps/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('predictions', models.ManyToManyField(blank=True, to='dr_app.predictionresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
